### ISSUE TITLE
git config's "--global" doesn't query includes

### ISSUE THREAD

**Issue by maxim** [seattlerb/omnifocus-github#7]
Should simply drop "--global" when querying git config. If your dotfiles are public, and you're keeping secrets separate, you can use [include] git section, but the included file will be ignored if `--[somefile]` is specified. There doesn't seem to be any specific reason to use `--global`. Another option is to add `--includes` to the command, but probably a worse option.

**Comment by zenspider** [comment]
Uhhh... blahblah git. PR?

**Comment by zenspider** [comment]
Anything?

**Comment by maxim** [comment]
Haven't had time to work on optimizing my OF setup lately. All this issue asks is to stop using `--global` when you call git. Just delete `--global` from code.

**Comment by maxim** [comment]
Well, here: https://github.com/seattlerb/omnifocus-github/pull/11

**Comment by zenspider** [comment]
merged #11.
