### ISSUE TITLE
Readme should clarify how to set passwords with some special characters

### ISSUE THREAD

**Issue by abolishme** [seattlerb/omnifocus-github#8]
Some command lines will assume special characters in a password like an ampersand indicate a command, and strip out the remaining part of passwords, for example:

```
git config --global omnifocus-github.password mypa&word
```

might actually set the global config to `omnifocus-github.password=mypa`. I solved this problem by putting the string in quotes, i'm not sure if this works for everyone, but it seems like an issue. The solution should be clarified in the readme, for those who aren't technically skilled in this area.

**Comment by zenspider** [comment]
You're welcome to send in a PR, but I just assume that everyone has at least a rudimentary working knowledge of UNIX if they want to use commandline tools.

**Comment by zenspider** [comment]
anything?

**Comment by zenspider** [comment]
No response. Closing.
