### ISSUE TITLE
Missing authentication parameters for account

### ISSUE THREAD

**Issue by yosefrajwulf** [seattlerb/omnifocus-github#9]
I am trying to use of sync with my github account. Using git config, I have set omnifocus-github.user to my token,  and omnifocus-github.password to x-oauth-basic. However, I am getting a "Missing authentication parameters for account" error. Could someone please help?

**Comment by zenspider** [comment]
Can you try it w/o the "omnifocus-" prefix? Looking at the code, it seems like it is only using "github."

**Comment by yosefrajwulf** [comment]
Thanks! I did the change and it now works. I would like to point out that the project README.md file was a bit confusing in this regard (and I should have checked the code instead). Would it be OK the update the README.md file to correct this misunderstanding and include a small usage example?

**Comment by zenspider** [comment]
So that worked? Then we have a doco problem. Reopening.

**Comment by zenspider** [comment]
Yeah. if you want to send in a PR, please do.

**Comment by yosefrajwulf** [comment]
I already did.

**Comment by yosefrajwulf** [comment]
Any updates on this?

**Comment by zenspider** [comment]
Thanks for the bump. Merged. Thanks!
